name: Scheduled Merge Remote Action
on:
  schedule:
    - cron: "0 0 * * *" # This will run daily at midnight
  workflow_dispatch:

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main            # default branch
          fetch-depth: 0 
      
      - name: Merge Upstream
        uses: ethan42/merge-upstream@v4
        with:
          upstream: dbrumley/mayhem-april-1 # set the upstream repo manually
          upstream-branch: main # upstream default branch
          branch: main          # default branch
